### ISSUE TITLE
Snort rule for slmammer

### ISSUE THREAD

**Issue by Mkhan21** [vrtadmin/snort-faq#10]
alert udp $EXTERNAL_NET any -> $HOME_NET 1434 (msg:"HELL-SQL Worm
Scan";content:"|684765745466b96c6c|";classtype:attempted-admin;)

alert udp $EXTERNAL_NET any -> $HOME_NET 1434 (msg:"MS-SQL Slammer
WormActivity";content:"|81f10301049b81f101|"; classtype:bad-unknown;
sid:9994; rev:1;)

can any one explain the structure of these signatures. i mean what is meant by different parts of these signatures? help will be really appreciated. 
Thanks

**Comment by finchy** [comment]
Dear Mkhan21,

I suggest that you address your question to the appropriate Snort mailing list found here:

https://www.snort.org/community

While I try, I can't get to everyone's email personally and this allows us to leverage everyone on the team as well as the whole open source community.

Thank you.
