### ISSUE TITLE
I'm a Newer in snort, please help me some questions, thanks

### ISSUE THREAD

**Issue by k51312** [vrtadmin/snort-faq#12]
1、the service_rpc.c ：relealize the SUN ONC RPC fragment to reassemble. and the funcion RpcStatefulInspection is the key API to relealize the fragment  to reassemble. 

static RpcStatus RpcStatefulInspection(RpcDecodeConfig *rconfig,
        RpcSsnData *rsdata, Packet *p)
it's third paramter p must be the buffer, which is  ( tcp payload +  first record marking (RM) ) ??  and where the p move to the fragment RM ?is the rpc_validate does the logic ?
2、rpc_init register theApp ID：APP_ID_SUN_RPC ， and  dcerpc_init register the App ID:APP_ID_DCE_RPC, those are two dynamic service plugins.  yet in the src\dynamic-preprocessors\dcerpc2 directory, the "dcerpc2" module has many files those files have what relation with
APP_ID_DCE_RPC ?  in dcerpc2 ：DCE2_Main --> DCE2_Process relealize the fragment reassemble for APP_ID_DCE_RPC ?

welcome get your answer to help me understand the RPC fragment and reassemble .thanks !

**Comment by vrtadmin** [comment]
Please direct your questions to the Snort mailing lists:  https://www.snort.org/community

**Comment by k51312** [comment]
https://www.snort.org.community, then click the snort-develop mail list , i have tried many times, but i can't open the link

**Comment by k51312** [comment]
https://sourceforge.net/p/snort/mailman/snort-devel/ this link is difficult to open successfully

**Comment by vrtadmin** [comment]
I've just tried it from two different networks.  Works perfectly fine for me:

https://lists.sourceforge.net/lists/listinfo/snort-devel
